### PR TITLE
CRL2-4818 allow creation of multiple companies for an employer account.

### PR DESCRIPTION
**Pull request by pankti459**

### CODE REVIEW

**Comment by chrisxh** [comment]
Testing with `https://ercmn-stage.careerleaf.com/app/api/v1/employers/` reveals:

- PUT/PATCH/DELETE not supported
- POST with payload having an employer account "name" property that already exists returns message `{"detail": {"company": "Name is not unique"}}`
  - Label in return message should indicate that "employer" name is not unique. 
  - This is OK if PUT/PATCH are supported

**Comment by chrisxh** [comment]
Testing with `https://ercmn-stage.careerleaf.com/app/api/v1/employers/` reveals:

Given POST where payload contains an employer name (`Employer.name`) value not already present in the CL instance (i.e., creating a new employer account), and a Company where `Company.is_default: 1`, and `Company.name` *does not match* `Employer.name`.  

The resulting Employer account is created, with Company entries having :
- `Employer.name`, (which appears to be the "default" company?) and   
- `Company.name`

Expected that the Company created and associated with the Employer account would have name of `Company.name`.  And, no Company having `Employer.name` would be created.


POST'ed payload
2019-09-06 10_25_18-Postman


Resulting Employer/Company listing:

image

**Comment by chrisxh** [comment]
Testing with `https://ercmn-stage.careerleaf.com/app/api/v1/employers/` reveals:

Given a valid `Employer.id` value as part of the POST payload.  Issuing the POST results in a HTTP Status Code 500.  Content response includes the html:
```
<h1>Something went wrong.</h1>
<p>
    Error details were sent to developers. We will try to fix the problem as soon as we can.
</p>
```

Expected a response status 20x and the employer, companies, users to be updated.

HTTP command issued was as follows (authentication header obscured).

```
curl -X POST \
  https://ercmn-stage.careerleaf.com/app/api/v1/employers/ \
  -H 'authentication: CL *****/******' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 4a6c0308-2d82-b57e-fb16-6582d8c080ef' \
  -d '{
   "id": "5d655862217f6362f689bd4a",
   "name": "Fridley Public Schools",
   "site_url": "https://www.fridley.k12.mn.us/",
   "old_id": "0014-01",
   "desc": "&lt;div id=&quot;text1&quot;&gt;&lt;h1&gt;WELCOME STATEMENT&lt;/h1&gt;&lt;p&gt;&lt;span style=&quot;font-size: large;&quot;&gt;Our school district&rsquo;s mission says in part that we aim to develop internationally-minded students and to that end we &lt;em&gt;&ldquo;challenge ourselves, our students, and our community to become caring and knowledgeable lifelong learners who inquire and take action to create a better world.&rdquo;&lt;/em&gt;&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;font-size: large;&quot;&gt;Fridley continues to welcome all our students and families who have chosen to make our schools their schools of choice. As International Baccalaureate (IB) World Schools, we demonstrate the ideals of the IB Learner Profile by caring about every single member of our school community and we are committed to supporting our students as best as we can.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;font-size: large;&quot;&gt;We want to assure all our Fridley students and families that they are welcome here and that we will continue to provide the same level of quality education in a safe and welcoming environment to all our students as we have always done.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;span style=&quot;font-size: large;&quot;&gt;&lt;br&gt;&lt;/span&gt;&lt;/p&gt;&lt;h1&gt;&lt;/h1&gt;&lt;h1&gt;&lt;/h1&gt;&lt;h1&gt;ABOUT US&lt;/h1&gt;&lt;p class=&quot;fs_style_1&quot;&gt;&lt;span style=&quot;font-size: large; color: #000000;&quot;&gt;&lt;span style=&quot;font-size: large; color: #000000;&quot;&gt;The Fridley School District serves the central area of the City of Fridley with two elementary schools (K-4), a middle school (5-8), a high school (9-12), an area learning center and a community center that serves community members ages birth to seniors. Fridley is known for a small-town atmosphere in the midst of a metro area. Fridley experiences unusually strong enrollment by nonresidents who cite high quality academics, positive school climate, and personalized attention to learning for each student, as their reasons for choosing the Fridley Schools.&lt;/span&gt;&lt;br&gt;&lt;br&gt;The Fridley School District offers the International Baccalaureate Programme to all students. The Primary Years Programme (PYP) is offered at our elementary schools, the Middle Years Programme (MYP) is offered at our middle school and high school, and the Diploma Programme (DP) and Career Programme (CP) are offered at the high school. Hayes and Stevenson Elementary Schools, Fridley Middle School and Fridley High School are all IB World Schools.&lt;/span&gt;&lt;br&gt;&lt;br&gt;&lt;span&gt;&lt;br&gt;&lt;span style=&quot;font-size: large; color: #000000;&quot;&gt;For more information, please contact the Communications Office:&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: large; color: #000000;&quot;&gt;&lt;a target=&quot;_blank&quot; href=&quot;mailto:communications@fridley.k12.mn.us&quot;&gt;&lt;span style=&quot;color: #000000;&quot;&gt;communications@fridley.k12.mn.us&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;br&gt;&lt;span style=&quot;font-size: large; color: #000000;&quot;&gt;763-502-5020&lt;/span&gt;&lt;br&gt;&lt;br&gt;&lt;/span&gt;&lt;span&gt;&lt;/span&gt;&lt;/p&gt;&lt;/div&gt;",
   "billing_address": {
      "postal_code": "55432",
      "street": "6000 West Moore Lake Drive",
      "street2": "",
      "city": "Fridley",
      "state": "Minnesota",
      "state_id": 75,
      "country": "United States",
      "country_code": "US",
      "phone": "763-502-5000",
      "fax": null
   },
   "created_on": "2019-08-27T16:20:50.315",
   "def_company": "Fridley Public Schools",
   "users": [
      {
         "first_name": "Default",
         "last_name": "Admin",
         "email": "chris@vitamink12.com",
         "access_group": "admin"
      }
   ],
   "companies": [
      {
         "name": "Fridley Public Schools",
         "url": "https://www.fridley.k12.mn.us/page.cfm?p=2290",
         "desc": null,
         "is_default": 1,
         "logo_url": "https://www.fridley.k12.mn.us/uploaded/themes/2014_redesign/images/FPS-logo.svg"
      }
   ]
}'

```

**Comment by pankti459** [comment]
> Testing with `https://ercmn-stage.careerleaf.com/app/api/v1/employers/` reveals:
> 
>     * PUT/PATCH/DELETE not supported
> 

> PUT/PATCH/DELETE requires id at the end
> https://ercmn-stage.careerleaf.com/app/api/v1/employers/5d72a147217f637187ecd377

>     * POST with payload having an employer account "name" property that already exists returns message `{"detail": {"company": "Name is not unique"}}`
>      
>       * Label in return message should indicate that "employer" name is not unique.
>       * This is OK if PUT/PATCH are supported


>  Good Point. Will change it to "employer".

**Comment by pankti459** [comment]
> Testing with `https://ercmn-stage.careerleaf.com/app/api/v1/employers/` reveals:
> 
> Given POST where payload contains an employer name (`Employer.name`) value not already present in the CL instance (i.e., creating a new employer account), and a Company where `Company.is_default: 1`, and `Company.name` _does not match_ `Employer.name`.
> 
> The resulting Employer account is created, with Company entries having :
> 
>     * `Employer.name`, (which appears to be the "default" company?) and
> 
>     * `Company.name`
> 
> 
> Expected that the Company created and associated with the Employer account would have name of `Company.name`. And, no Company having `Employer.name` would be created.
> 
> POST'ed payload
> 2019-09-06 10_25_18-Postman
> 
> Resulting Employer/Company listing:
> 
> image

> This is the default behavior in careerleaf. When an Employer is created, default company with the same name gets created.

**Comment by chrisxh** [comment]
> PUT/PATCH/DELETE requires id at the end
> https://ercmn-stage.careerleaf.com/app/api/v1/employers/5d72a147217f637187ecd377

Issuing PATCH (and PUT) with the id at the end responds with HTTP Status Code 500.  Content response includes the html:
```
<h1>Something went wrong.</h1>
<p>
    Error details were sent to developers. We will try to fix the problem as soon as we can.
</p>
```

Example HTTP PATCH payload:

```
curl -X PATCH \
  https://ercmn-stage.careerleaf.com/app/api/v1/employers/5d655862217f6362f689bd4a \
  -H 'authentication: CL ******/*********' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: f19b0ae0-7d2d-da76-9ac4-2a087d1bc60f' \
  -d '{
   "name": "Fridley Public Schools",
   "site_url": "https://www.fridley.k12.mn.us/",
   "old_id": "0014-01"
}'
```

**Pull request merged**
